version: '3'

services:
  web:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - database
    networks:
      - mynet

  database:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=password
    volumes: 
      - db_data:/var/lib/mysql 
    networks:
      - mynet
networks:
  mynet:
    driver: "bridge"
volumes:
  db_data: {}